### ISSUE TITLE
ColdStorage: Need an ability to search archives

### ISSUE THREAD

**Issue by rajinders** [mspnp/data-pipeline#38]
We have a need to occasionally search the archived message to look for a specific message or messages. My initial thought is to consider using Azure search service. This service currently does support crawling blob containers and indexing them. So the only way this can work is if the cold storage worker role invokes the search API to create indexes so we can easily search messages at a future time. Are there any other options we should be considering?

**Comment by bennage** [comment]
The idea behind *cold storage* is that it is will be used infrequently and with something like Hadoop.
If you have a need to query for events on a more regular basis, I would consider having another event consumer pumping events to something like Elasticsearch (this is sometimes referred to as the *warm* path).

I spoke to someone who took the cold storage consumer from this project and modified it to send events to an Elasticsearch endpoint instead of blobs. They told me that it was not hard to do and that it worked out well. This approach involves having another independent event process host (consumer group) just for the warm path. However, that's part of the idea underlying event hubs.

I haven't spent time with Azure Search yet (it's on my backlog), but a similiar approach might work there.
